spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
    time-zone: America/Sao_Paulo
  cloud:
    gcp:
      project-id: pass-223419
      credentials:
        location: classpath:static/google-service-account-pass-223419-b7c8a7bb1d1c.json
  redis:
      host: localhost
      port: 6379

server:
  connection-timeout: 60000
  session.timeout: 60000
  servlet:
    context-path: /api
  port: 8080

management:
  security:
    enabled: false
  context-path: /api

endpoints:
  enabled: false
  health:
    enabled: true
